[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Use complex numbers
num = "0.4"

# Reading and writing a wide variety of image formats
image = "0.13.0"